### ISSUE TITLE
Exited validators get reported as missing attestations

### ISSUE THREAD

**Issue by karalabe** [kilnfi/eth-validator-watcher#76] opened 2023-10-04 10:54 UTC
TL;DR:

```
🚶 Our validator 0xpubkey is exited
 [...]
☹️ Our validator 0xpubkey and 0 more missed attestation
```

**Comment by nalepae** [comment] 2023-10-10 12:10
Thanks for your issue!

Closing as duplicate of #67

**Closed by nalepae** 2023-10-10 12:10 UTC
